### ISSUE TITLE
Fillarm support

### ISSUE THREAD

**Issue by stijnwop** [stijnwop/hoseSystem#34]
- [x] Suction arm to suck from the manure pit
- [x] Add suction fillType categories

**Comment by TomCat67** [comment]
Hmm .. Now that the SP slurry vehicles is in order, I've been looking a bit to try and make the fillarm work. Especially the Kotte Taurus, and a 4 axle slurry trailer is my main targets right now - but they both have fillarms with multiple joints, and can be rotated 180 degrees left/right. Is it to soon to try and make them work ? Is the scripts supporting this yet ? .. I have been looking for some kind of vehicle.XML entries here (like the pump must have some text added to work) but this is perhaps not necessary ? I'll patiently wait, if it's too early to try this feature out .. Regards TomCat67

**Comment by stijnwop** [comment]
No it's definitely not to soon.

Make sure to grab the latest hosesystemvehicle script for this repository and add the xml entries:

<hoseSystem hasFillArm="true" hasPumpMotor="true"/>
<hoseSystemFillArm type="arm" supportedFillTypeCategories="slurryTank" index="2>0" />

The index defines a node at the end of your fillarm

**Comment by stijnwop** [comment]
<hoseSystem hasFillArm="true" hasPumpMotor="true"/>
<hoseSystemFillArm type="arm" supportedFillTypeCategories="slurryTank" index="2>0" />

**Comment by TomCat67** [comment]
Yes .. Now I'm back on track - gonna try this this out right now .. Thank you very much .. TomCat67

**Comment by TomCat67** [comment]
Hmm .. Now, this is not a cry for support, but needs to know if I'm doing this right .. Placed a reference node (like we do for hoses) at the end of the last arm (where the arm slurry pipe ends) in the TG for the last arm. Then I put in the node information in vehicle.XML file, where it said 2>0 before - is this also correct ? .. The log says everything is good (arm is accepted and so on) but then I realized the arm won't accept to fill from a slurrytank, because it's an arm for docking - and it can't go deep enough so it can get in a tank .. Then I tried with the slurrycontainer (the one you made for HoseSystem) But the docking fill/overload tube isn't working - you have "commented" this section out - tried to "uncomment" it, but then I get an error about a trigger not being a physics trigger .. So can't really tell if the arm works or not .. I'll get there (I think) but struggling a bit ... (it doesn't kill me, so I'm guessing I'll be a lot stronger ..) Regards TomCat67

**Comment by stijnwop** [comment]
What fillArm type do you want to implement actually? Docking or a normal fillarm?

From there I can help you further. ^^

**Comment by TomCat67** [comment]
Sorry - that was perhaps a little unclear .. On the Kotte it is a docking arm - So it would need to use the docking system on the container ... But on another mod (I've haven't worked on yet) it's a fillarm (not docking) so I plan to use the mod with the regular arm (not docking) to fill the container (shuttle from tank to container) and the Kotte with the docking arm, to fill itself via the docking system on the container ... Is this not possible ?

**Comment by TomCat67** [comment]
Oh - was a bit unclear again .... Sorry ..
Three mods working together --- 
Mod number 1 = Kotte Taurus SP slurry vehicle with Hosesystem and docking arm.
Mod number 2 = Slurry trailer with normal/regular arm (slurrypump at the end of the arm - no docking)
Mod number 3 = Slurrycontainer with Hosesystem, docking system and fillable from the top .. 
Regards TC67

**Comment by TomCat67** [comment]
Tried to narrow it down a bit, and regardless what I do when I'm uncommenting this line in the container : 

<hoseSystemReference index="0>3|6|1" type="dock" inRangeDistance="0.15" deformatioNode="0>3|6|0|0" deformatioYOffset="0.3" deformatioYMaxPush="0.09" />

I get this in the log : 

HoseSystem [Debug] : {
|  hasHoseSystemFillArm : false
|  hasHoseSystemConnectors : true
|  hasHoseSystemPumpMotor : false
}
HoseSystem [Debug] : Connector specialization added to: FS17_garantFieldContainer_HS
C:/Users/HCHPC/Documents/My Games/FarmingSimulator2017/mods/FS17_garantFieldContainer_HS/garantFieldContainer.i3d (51.71) ms
Warning (physics): Add trigger callback failed, object reference is not a physics trigger.

**Comment by stijnwop** [comment]
Take a look at this one:
https://www.dropbox.com/s/9y5f38f49vavytq/FS17_garantFieldContainer_HS_update.zip?dl=0

Thats the container.
The docking arm needs the same setup as describe above according the fillArm. Only change the type to dock.
Also make sure that the arm has collision since the dock reference on the container needs it to detect if the arm is in range.

**Comment by TomCat67** [comment]
Thank you very much ... This has proved to be challenge (but then again, it's quite fun) .. Downloaded the new container, and compared the container xml to the vehicles xml files, and edited them to match .. It makes sense, that the arm should have collision - just to be sure, it's the arm that must have collision ? It's not enough that there is a trigger at the end of the arm with collision ? And by the way, if it's the arm (which I am presuming it is) is the trigger at end of the arm necessary, or is it obsolete ?  Sorry for what may seem as kind of stupid questions ... Regards from TC67

**Comment by stijnwop** [comment]
Only on the dock arm types the collision is necessary. Well it doesn't matter if there's just collision at the end or on the whole arm.. but when you look from the physics point of view it would make sense to put collision on the whole arm.

On the normal fillarm it's functional wise obsolete. But same story here according the physics..

**Comment by TomCat67** [comment]
Hmmmm ... Got the trailer with the fillarm (type=arm) to function .. It fills, and unloads in pits and container - and it's looking good .. Only thing is, that the arm can go right through the side of the container, and through the top of a concrete slurry pit - tried the collision mesh for fillable (1, 8, 13, 23) and then the collision from the "reference TG" from your container - but no change .. Can't figure out, why the docking arm (type=dock) on the SP slurry vehicle won't work - tried a lot, in order to make it function, but with no succes .. The same story with the collision - but if I change the type from arm to dock, it works when the arm is put in the slurry in the container ... Running low on ideas ..

**Comment by stijnwop** [comment]
You will need to add collision on the fillArm like all the normal moving tools have with a delayed mesh. Just normal vehicle collision will do.

On the dock same story just the normal collision mask will do. Make sure to put it at the end aswell. There's not much to do in order to make it work.

Perhaps wait a couple of days till the update of the hose system is released. I included some example mods.. and will update the tutorial after that. ;)

**Comment by TomCat67** [comment]
Okay - one or two things that I'm surely do not understand - got to figure this collision thing out (the arm has no collision from the start, and isn't covered by the rigid body collision in index 0> .. But that's not your problem, I'll figure it out my self (need to expand my abilities on this) sorry if I asked questions that do not belong here (basic knowledge questions) But really thought I could do this - thank you for your help, and thank you for a great mod - Best wishes from TC67

**Comment by stijnwop** [comment]
No problem. If you have further issues or suggestions feel free to open a new issue. ;)

**Comment by TomCat67** [comment]
Ahemm .. Feeling so stupid - got it sorted out .. You told me (several times) but I didn't understand the collision thing .. Presuming the whole mod had collision, if the main part of the mod had it .. Oh dear, I was in for a steep learning curve .. Made the collision mesh directly in GE (didn't know that was possible until now) and now both mods, with the two different arm types work - and it is amazing how good it looks, feels and works ..  .. Now, if this (thread ??) has turned in to a form for support (question/answer) thing, and it may not be the purpose of being able to comment on your work - you could just delete this line of "what do I do now" questions .. I'll surely understand ... Best regards (and thanks again) -TC67

**Comment by stijnwop** [comment]
Included in latest release.
